// flow-typed signature: b8565bcccd93fcaf6ee1c39e1a5a4a97
// flow-typed version: <<STUB>>/react-csv-reader_v^0.3.2/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-csv-reader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-csv-reader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-csv-reader/dist/react-csv-reader' {
  declare module.exports: any;
}

declare module 'react-csv-reader/src/index' {
  declare module.exports: any;
}

declare module 'react-csv-reader/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-csv-reader/dist/react-csv-reader.js' {
  declare module.exports: $Exports<'react-csv-reader/dist/react-csv-reader'>;
}
declare module 'react-csv-reader/src/index.js' {
  declare module.exports: $Exports<'react-csv-reader/src/index'>;
}
declare module 'react-csv-reader/webpack.config.js' {
  declare module.exports: $Exports<'react-csv-reader/webpack.config'>;
}
